# Generated by Django 2.2 on 2020-03-30 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodpost', '0003_foodpost_publishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='publishing_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
