# Generated by Django 2.2 on 2020-04-05 08:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodpost', '0004_auto_20200330_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
